version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=prasad
      - POSTGRES_PASSWORD=prasad
      - POSTGRES_DB=patients
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
